# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/frm_potrace.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spin_turdsize = QtWidgets.QSpinBox(Form)
        self.spin_turdsize.setMinimumSize(QtCore.QSize(64, 0))
        self.spin_turdsize.setMinimum(1)
        self.spin_turdsize.setMaximum(3)
        self.spin_turdsize.setProperty("value", 2)
        self.spin_turdsize.setObjectName("spin_turdsize")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_turdsize)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.combo_turnpolicy = QtWidgets.QComboBox(Form)
        self.combo_turnpolicy.setObjectName("combo_turnpolicy")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.combo_turnpolicy.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.combo_turnpolicy)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.spin_alphamax = QtWidgets.QSpinBox(Form)
        self.spin_alphamax.setMinimumSize(QtCore.QSize(64, 0))
        self.spin_alphamax.setMaximum(10)
        self.spin_alphamax.setProperty("value", 10)
        self.spin_alphamax.setObjectName("spin_alphamax")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_alphamax)
        self.check_opticurve = QtWidgets.QCheckBox(Form)
        self.check_opticurve.setObjectName("check_opticurve")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.check_opticurve)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.slider_blacklevel = QtWidgets.QSlider(Form)
        self.slider_blacklevel.setMaximum(16)
        self.slider_blacklevel.setPageStep(1)
        self.slider_blacklevel.setProperty("value", 8)
        self.slider_blacklevel.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blacklevel.setObjectName("slider_blacklevel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slider_blacklevel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)

        self.retranslateUi(Form)
        self.combo_turnpolicy.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "potrace"))
        self.label.setText(_translate("Form", "Turdsize"))
        self.label_2.setText(_translate("Form", "Turnpolicy"))
        self.combo_turnpolicy.setItemText(0, _translate("Form", "black"))
        self.combo_turnpolicy.setItemText(1, _translate("Form", "White"))
        self.combo_turnpolicy.setItemText(2, _translate("Form", "Left"))
        self.combo_turnpolicy.setItemText(3, _translate("Form", "Right"))
        self.combo_turnpolicy.setItemText(4, _translate("Form", "Minority"))
        self.combo_turnpolicy.setItemText(5, _translate("Form", "Majority"))
        self.combo_turnpolicy.setItemText(6, _translate("Form", "Random"))
        self.label_3.setText(_translate("Form", "Alphamax"))
        self.check_opticurve.setText(_translate("Form", "Opticurve"))
        self.label_4.setText(_translate("Form", "BlackLevel"))
        self.pushButton.setText(_translate("Form", "Trace"))
